name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Eslint
      run: yarn --ignore-engines add eslint
    - name: Run ESLint
      run: npx eslint . --ext .ts
