name: publish

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  Build-and-Push-SafeBot-to-GHCR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
        
      - name: Lint
        run: |
          yarn install
          yarn lint:fix
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "automate: lint"
          git push

      - name: Login to GitHub Container Registrys
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push SafeBot to GHCR
        run: |
          docker build . --tag ghcr.io/teamsafecord/safebot:latest
          docker push ghcr.io/teamsafecord/safebot:latest
