name: publish

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  Build-and-Push-SafeBot-to-GHCR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: getsentry/action-eslint-fix@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push SafeBot to GHCR
        run: |
          docker build . --tag ghcr.io/teamsafecord/safebot:latest
          docker push ghcr.io/teamsafecord/safebot:latest
